---
- name: Move local home
  command: mv /home /localhome
  args:
    creates: /localhome

- name: Set SELinux context for local home
  ansible.builtin.command:
    cmd: "chcon -t home_root_t /localhome/home"

- name: Restore SELinux context for local home
  command: restorecon -R /localhome/home

- name: Create symlink for home
  ansible.builtin.file:
    src: "/localhome/home"
    dest: "/home"
    state: link

- name: Create /localhome/data directory
  ansible.builtin.file:
    path: "/localhome/data"
    state: directory

- name: Set permissions for /localhome/data
  ansible.builtin.file:
    path: "/localhome/data"
    mode: "1777"